name: Deploy to S3

on:
  push:
    branches:
      - main

env:
  AWS_BUCKET_NAME_STATIC: ftr-rocketseat-upload-widget-web-static/
  AWS_BUCKET_NAME_CDN: ftr-rocketseat-upload-widget-web-cdn/
  SOURCE_FOLDER: ./dist

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Install Node
        id: install-node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        id: install-pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        id: install-dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Build app
        id: build-app
        run: pnpm build

      - name: Config AWS Credentials
        id: config-aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Sync files to S3 static
        id: sync-files-to-s3-static
        run: |
          aws s3 sync ${{ env.SOURCE_FOLDER }} s3://${{ env.AWS_BUCKET_NAME_STATIC }} --delete

      - name: Sync files to S3 CDN
        id: sync-files-to-s3-cdn
        run: |
          aws s3 sync ${{ env.SOURCE_FOLDER }} s3://${{ env.AWS_BUCKET_NAME_CDN }} --delete

      - name: Invalidate CDN cache
        id: invalidate-cdn-cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/*"
